global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'eureka-server:8761' ]

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'api-gateway:19000' ]

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'user-service:19100' ]

  - job_name: 'waiting-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'waiting-service:19200' ]

  - job_name: 'restaurant-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'restaurant-service:19300' ]

  - job_name: 'timeslot-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'timeslot-service:19400' ]

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'reservation-service:19500' ]

  - job_name: 'order-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'order-service:19700' ]

  - job_name: 'catalog-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'catalog-service:19800' ]

  - job_name: 'inventory-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'inventory-service:19900' ]
